'use client';

import { Suspense, useState, useEffect } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { ArrowLeft, CheckCircle, PackageOpen, User, CalendarClock, Car } from "lucide-react";

import { supabase } from "@/lib/auth";

function ShipmentDetailContent() {
    const router = useRouter();
    const searchParams = useSearchParams();
    const [isConfirmed, setIsConfirmed] = useState(false);
    const [driverName, setDriverName] = useState("Loading...");

    // ดึงข้อมูลจาก URL
    const licensePlate = searchParams.get('licensePlate') || "-";
    const departTime = searchParams.get('departTime') || "-";
    const driverId = searchParams.get('driverId') || "-";

    // ฟอร์แมตวันที่ให้สวยงาม
    const formattedDate = departTime !== "-"
        ? new Date(departTime).toLocaleString('en-GB', { dateStyle: 'medium', timeStyle: 'short' })
        : "-";

    useEffect(() => {
        // Fetch Driver Name
        const fetchDriver = async () => {
            if (driverId !== "-") {
                const { data, error } = await supabase
                    .from('driver')
                    .select('driver_name')
                    .eq('driver_id', driverId)
                    .single();
                if (data && !error) {
                    setDriverName(data.driver_name);
                } else {
                    setDriverName("Unknown");
                }
            }
        };
        fetchDriver();
    }, [driverId]);

    const handleConfirm = async () => {
        setIsConfirmed(true);

        try {
            const { error } = await supabase
                .from('shipment')
                .insert({
                    // Note: shipment_id is generated by a trigger trg_set_shipment_id
                    license_plate: licensePlate,
                    depart_time: departTime,
                    driver_id: driverId
                });

            if (error) throw error;

            alert(`✅ Shipment Created Successfully!`);
            router.push('/dashboard/shipment');
        } catch (error: any) {
            console.error("Error creating shipment:", error);
            alert("Failed to create shipment: " + error.message);
            setIsConfirmed(false);
        }
    };

    return (
        <div className="w-full h-full min-h-[80vh] flex flex-col items-center justify-center p-6 animate-in slide-in-from-right-8 duration-500">
            <div className="w-full max-w-3xl text-center">

                <h1 className="text-4xl md:text-5xl font-bold text-[#1a237e] mb-10 drop-shadow-sm flex justify-center items-center gap-4">
                    <PackageOpen className="w-12 h-12 text-indigo-500" />
                    Shipment Run Overview
                </h1>

                <div className="bg-white rounded-[32px] shadow-lg border border-gray-100 p-8 md:p-12 flex flex-col gap-8 relative text-left">

                    <div className="flex flex-col gap-6 bg-indigo-50/50 p-6 md:p-8 rounded-3xl border border-indigo-100">

                        {/* License Plate */}
                        <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center border-b border-indigo-200/50 pb-4 gap-2">
                            <span className="text-xl font-bold text-gray-500 flex items-center gap-2">
                                <Car className="w-6 h-6 text-indigo-500" />
                                License Plate
                            </span>
                            <span className="text-2xl font-bold text-gray-900 text-right">
                                {licensePlate}
                            </span>
                        </div>

                        {/* Depart Time */}
                        <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center border-b border-indigo-200/50 pb-4 gap-2">
                            <span className="text-xl font-bold text-gray-500 flex items-center gap-2">
                                <CalendarClock className="w-6 h-6 text-indigo-500" />
                                Departure Schedule
                            </span>
                            <span className="text-2xl font-bold text-indigo-700 text-right">
                                {formattedDate}
                            </span>
                        </div>

                        {/* Driver */}
                        <div className="flex flex-col sm:flex-row sm:justify-between sm:items-start gap-2">
                            <span className="text-xl font-bold text-gray-500 flex items-center gap-2 whitespace-nowrap">
                                <User className="w-6 h-6 text-indigo-500 shrink-0" />
                                Assigned Driver
                            </span>
                            <div className="flex flex-col sm:text-right sm:max-w-[60%]">
                                <span className="text-xl font-bold text-gray-900 leading-relaxed">
                                    {driverName}
                                </span>
                                <span className="text-md text-gray-400 font-medium">
                                    ID: {driverId}
                                </span>
                            </div>
                        </div>

                    </div>

                    {/* Navigation */}
                    <div className="flex justify-between items-center w-full mt-4">
                        <button
                            onClick={() => router.back()}
                            className="w-16 h-16 bg-white rounded-[24px] shadow-md border border-gray-100 flex items-center justify-center hover:bg-gray-50 hover:shadow-lg transition-all hover:-translate-x-1"
                        >
                            <ArrowLeft className="w-8 h-8 text-black stroke-[3px]" />
                        </button>

                        <button
                            onClick={handleConfirm}
                            disabled={isConfirmed}
                            className="h-16 px-8 bg-white rounded-[24px] shadow-md border border-gray-100 flex items-center gap-3 hover:bg-green-50 hover:shadow-lg hover:border-green-200 transition-all hover:translate-x-1 group disabled:opacity-50"
                        >
                            <span className="text-xl font-bold text-gray-800 group-hover:text-green-700">Confirm Run</span>
                            <CheckCircle className="w-8 h-8 text-black stroke-[3px] group-hover:text-green-600 transition-colors" />
                        </button>
                    </div>

                </div>
            </div>
        </div>
    );
}

export default function ShipmentDetailPage() {
    return (
        <Suspense fallback={<div className="text-xl font-bold text-gray-500 text-center">Loading Detail...</div>}>
            <ShipmentDetailContent />
        </Suspense>
    );
}
